logging:
  level:
    ROOT: INFO
    com.location: DEBUG

spring:
  profiles:
    active: "dev"

application:
  apiPath:
    fourSquare: "https://api.foursquare.com/v2/venues/search"
    google: "https://maps.googleapis.com/maps/api/geocode/json"
  clientId:
  clientSecret:
  googleKey:

server:
  port: 8081